###
GET http://localhost:8080/products

###

POST http://localhost:8080/products HTTP/1.1
content-type: application/json

{
    "id": 4,
    "name": "Telewizor",
    "desc": "Telewizor plazmowy",
    "price": 5000
}

###

PUT http://localhost:8080/products
content-type: application/json

{
    "id": 3,
    "name": "Telewizor",
    "desc": "Telewizor zmieniony",
    "price": 2137
}

###
DELETE http://localhost:8080/products/3 HTTP/1.1