###
GET http://localhost:8080/products
###
GET http://localhost:8080/categories

###

POST http://localhost:8080/products HTTP/1.1
content-type: application/json

{
    "name": "Telewizor",
    "description": "Telewizor plazmowy",
    "price": 5000
}

###

POST http://localhost:8080/categories HTTP/1.1
content-type: application/json

{
    "name": "Plazma"
}

###

PUT http://localhost:8080/products
content-type: application/json

{
    "id": "60ba29cdcd93ac36f8dbc9ea",
    "name": "Telewizor Plaski",
    "description": "Telewizor zmieniony",
    "price": 2137
}

###
DELETE http://localhost:8080/products HTTP/1.1
content-type: application/json

{
    "id": "60ba29cdcd93ac36f8dbc9ea"
}
///////////////////////// CARS
###
GET http://localhost:8080/cars
###

POST http://localhost:8080/cars HTTP/1.1
content-type: application/json

{
    "id": 1,
    "model": "Lexus",
    "fuel": "LPG",
    "desc": "złoto panie",
    "price": 5000
}
